name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML & CSS Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload all files in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
